//! Workaround for a Node.js / libuv ↔ WinFSP interaction: libuv's
//! native `uv_fs_realpath` calls `GetFinalPathNameByHandleW(...,
//! VOLUME_NAME_DOS)`, which returns an error libuv can't map for files
//! on WinFSP mounts (our Workspace, but also the WinFSP-shipped `memfs`
//! sample, sshfs-win, rclone, etc.). The error surfaces in Node as
//! `UNKNOWN: unknown error, realpath '<path>'` with `errno === -4094`.
//!
//! Copilot CLI's ACP `session/new` handler calls `fs/promises.realpath`
//! on the supplied `cwd` to canonicalize it; when that fails it
//! rejects with `"Directory does not exist or cannot be accessed"`,
//! which means we can't point Copilot at a WinFSP-mounted workspace
//! *at all* without addressing this.
//!
//! The shim below patches `fs.promises.realpath` and
//! `fs.realpathSync.native` so that `UNKNOWN` errors fall back to
//! `fs.realpathSync` — which is Node's JS-level implementation and
//! does *not* call `GetFinalPathNameByHandleW` (it walks the tree with
//! `statSync`, a code path we've verified works against WinFSP). Every
//! other error is re-thrown unchanged.
//!
//! The shim is injected via `NODE_OPTIONS=--require <path>` on Windows
//! only; non-Windows hosts never load it. It is deliberately tiny and
//! does nothing for any other syscall or error class.

/// Embedded JavaScript shim. Kept small and dependency-free so we can
/// reason about it line-by-line. The constant is the sole source of
/// truth — [`prepare_nodejs_options`] just materializes it to disk.
pub const SHIM_JS: &str = r#"// devdev-realpath-shim.js — auto-generated by devdev-cli.
// Patches fs.promises.realpath and fs.realpathSync.native to fall back
// to the JS-emulated fs.realpathSync when libuv's native realpath fails
// with UNKNOWN (errno -4094) on WinFSP mounts. Any other error is
// re-thrown unchanged. Non-UNKNOWN paths are unaffected.
'use strict';
try {
  const fs = require('fs');
  const fsp = require('fs/promises');
  const origNativeSync = fs.realpathSync && fs.realpathSync.native;
  const origPromisesRealpath = fsp.realpath;
  const logPath = process.env.DEVDEV_SHIM_LOG;
  function log(msg) {
    if (!logPath) return;
    try { fs.appendFileSync(logPath, '[' + new Date().toISOString() + '] ' + msg + '\n'); } catch (_) {}
  }
  log('loaded (pid=' + process.pid + ')');
  const isUnknown = (e) =>
    e && (e.code === 'UNKNOWN' || e.errno === -4094);
  function patchedSyncNative(p, opts) {
    try {
      return origNativeSync(p, opts);
    } catch (e) {
      if (!isUnknown(e)) throw e;
      return fs.realpathSync(p, opts);
    }
  }
  async function patchedPromisesRealpath(p, opts) {
    try {
      return await origPromisesRealpath(p, opts);
    } catch (e) {
      if (!isUnknown(e)) throw e;
      return fs.realpathSync(p, opts);
    }
  }
  if (typeof origNativeSync === 'function') {
    fs.realpathSync.native = patchedSyncNative;
  }
  if (typeof origPromisesRealpath === 'function') {
    fs.promises.realpath = patchedPromisesRealpath;
    fsp.realpath = patchedPromisesRealpath;
  }
  // Node's ESM namespace for built-in modules is a snapshot taken at
  // bootstrap. Imports like `import {realpath} from 'node:fs/promises'`
  // do NOT see later mutations to fs.promises.realpath unless we call
  // this API. Without it, the patch is silently ignored by ESM callers.
  try { require('module').syncBuiltinESMExports(); } catch (_) {}
  log('patched');
} catch (e) {
  try { process.stderr.write('[devdev-shim] error: ' + (e && e.stack || e) + '\n'); } catch (_) {}
}
"#;

/// On Windows, materialize [`SHIM_JS`] to a stable temp path and return
/// `(key, value)` env-override pairs that `require` it in the spawned
/// Node process. On non-Windows hosts, returns an empty vector.
///
/// The returned `NODE_OPTIONS` value *appends* to any existing
/// `NODE_OPTIONS` from the parent env so we don't silently drop user
/// configuration.
pub fn prepare_nodejs_options() -> Vec<(String, String)> {
    if !cfg!(target_os = "windows") {
        return Vec::new();
    }
    let shim_path = match write_shim_to_temp() {
        Ok(p) => p,
        Err(err) => {
            tracing::warn!(
                target: "devdev_cli::realpath_shim",
                error = %err,
                "failed to write WinFSP realpath shim; Copilot may reject WinFSP cwd"
            );
            return Vec::new();
        }
    };
    // Node's NODE_OPTIONS parser treats backslash as an escape character,
    // which silently strips the drive-letter separators from a Windows
    // path like `C:\Users\...`. Node accepts forward slashes in require
    // paths on Windows, so normalize before quoting.
    let shim_str = shim_path.to_string_lossy().replace('\\', "/");
    let quoted = format!("\"{}\"", shim_str.replace('"', "\\\""));
    tracing::info!(
        target: "devdev_cli::realpath_shim",
        shim = %shim_str,
        "injecting WinFSP realpath shim into Copilot via NODE_OPTIONS"
    );
    let require_flag = format!("--require {quoted}");
    let combined = match std::env::var("NODE_OPTIONS") {
        Ok(existing) if !existing.trim().is_empty() => {
            format!("{existing} {require_flag}")
        }
        _ => require_flag,
    };
    let mut result = vec![("NODE_OPTIONS".to_string(), combined)];
    // If the caller pre-set a log path in our own process, propagate it
    // so the shim writes there. Tests set this to collect shim diagnostics.
    if let Ok(log) = std::env::var("DEVDEV_SHIM_LOG")
        && !log.is_empty()
    {
        result.push(("DEVDEV_SHIM_LOG".to_string(), log));
    }
    result
}

fn write_shim_to_temp() -> std::io::Result<std::path::PathBuf> {
    let dir = std::env::temp_dir().join("devdev-realpath-shim");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("shim.js");
    // Always rewrite: trivial cost, guarantees we stay in sync with any
    // CLI upgrade that tweaks the shim body.
    std::fs::write(&path, SHIM_JS)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shim_text_is_nonempty_and_strict() {
        assert!(SHIM_JS.contains("'use strict'"));
        assert!(SHIM_JS.contains("fs.promises.realpath"));
        assert!(SHIM_JS.contains("fs.realpathSync.native"));
        assert!(SHIM_JS.contains("UNKNOWN"));
    }

    #[cfg(not(target_os = "windows"))]
    #[test]
    fn prepare_is_noop_off_windows() {
        assert!(prepare_nodejs_options().is_empty());
    }

    #[cfg(target_os = "windows")]
    #[test]
    fn prepare_writes_shim_and_returns_node_options() {
        let overrides = prepare_nodejs_options();
        assert_eq!(overrides.len(), 1);
        assert_eq!(overrides[0].0, "NODE_OPTIONS");
        assert!(overrides[0].1.contains("--require"));
        // The referenced file must exist and contain the shim body.
        // Extract the quoted path between the first and last `"`.
        let val = &overrides[0].1;
        let first = val.find('"').expect("NODE_OPTIONS contains quoted path");
        let last = val.rfind('"').expect("NODE_OPTIONS closes the quote");
        assert!(last > first, "malformed quoting: {val}");
        let path = &val[first + 1..last];
        let body = std::fs::read_to_string(path).expect("shim file readable");
        assert!(body.contains("patchedPromisesRealpath"));
    }
}
