//! Real-workload FUSE test (Linux only): build & run a hello-world crate
//! entirely inside the mount. Exercises the `Arc<Mutex<Fs>>` driver under
//! the parallel fs traffic generated by cargo + rustc.
//!
//! **Currently `#[ignore]`**. This test exposes the known containment
//! gap: child processes run in the host mount namespace, so the
//! curated `HOME=/home/agent` that `Workspace::exec` injects resolves
//! against host root, not against the mount. cargo/rustup then tries
//! to `mkdir $HOME/.rustup` on the host and fails (`ENOENT` or
//! `EACCES` depending on host state). The driver itself is correct;
//! the gap is in child-process isolation.
//!
//! This test is intentionally left in place so that once we add a
//! containment layer (chroot / pivot_root / user-namespace mount
//! binding), flipping off the `#[ignore]` is the one-line proof the
//! containment works. Run locally via:
//!
//! ```text
//! cargo test -p devdev-workspace --test cargo_build -- --ignored
//! ```

#![cfg(target_os = "linux")]

use std::ffi::OsStr;

use devdev_workspace::Workspace;

fn workspace_with_basics() -> Workspace {
    let mut ws = Workspace::new();
    {
        let fs = ws.fs();
        let mut g = fs.lock().unwrap();
        g.mkdir_p(b"/home/agent", 0o755).unwrap();
        g.mkdir_p(b"/home/agent/.cargo", 0o755).unwrap();
        g.mkdir_p(b"/home/agent/hello/src", 0o755).unwrap();
        g.write_path(
            b"/home/agent/hello/Cargo.toml",
            b"[package]\nname = \"hello\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\n",
        )
        .unwrap();
        g.write_path(
            b"/home/agent/hello/src/main.rs",
            b"fn main() { println!(\"Hello from inside the mount!\"); }\n",
        )
        .unwrap();
    }
    ws.mount().expect("mount");
    ws
}

fn host_cargo_path() -> String {
    let home = std::env::var("HOME").expect("HOME must be set to locate host cargo");
    format!("{home}/.cargo/bin/cargo")
}

#[test]
#[ignore = "blocked on containment phase: child process's `/` is the host \
root, so $HOME=/home/agent resolves off-mount. Un-ignore when chroot / \
pivot_root / user-ns mount binding lands."]
fn cargo_builds_hello_world_inside_mount() {
    let ws = workspace_with_basics();
    let cargo = host_cargo_path();

    let mut out = Vec::new();
    let code = ws
        .exec(
            OsStr::new(&cargo),
            &[OsStr::new("build"), OsStr::new("--offline")],
            b"/home/agent/hello",
            &mut out,
        )
        .expect("exec cargo build");

    if code != 0 {
        let dump = String::from_utf8_lossy(&out);
        let truncated: String = dump.chars().take(4096).collect();
        panic!("cargo build failed with exit {code}; output (truncated):\n{truncated}");
    }

    // Confirm the produced binary landed in MemFs via the FUSE driver.
    {
        let fs = ws.fs();
        let g = fs.lock().unwrap();
        g.resolve(b"/home/agent/hello/target/debug/hello")
            .expect("cargo should have written the binary into the mount");
    }

    let mut out2 = Vec::new();
    let code2 = ws
        .exec(
            OsStr::new("/home/agent/hello/target/debug/hello"),
            &[],
            b"/home/agent/hello",
            &mut out2,
        )
        .expect("exec built binary");
    let stdout = String::from_utf8_lossy(&out2).to_string();
    assert_eq!(code2, 0, "built binary exited {code2}; output:\n{stdout}");
    assert!(
        stdout.contains("Hello from inside the mount!"),
        "binary produced unexpected output:\n{stdout}"
    );
}
